name: Daily Activity

on:
  schedule:
    - cron: "0 1 * * *"   # chạy mỗi ngày 08:00 GMT+7 ≈ 01:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  heartbeat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update heartbeat
        run: |
          mkdir -p .meta
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .meta/heartbeat.txt
          echo "Last update: $(cat .meta/heartbeat.txt)"

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .meta/heartbeat.txt
            git commit -m "chore: daily heartbeat"
            git push
          else
            echo "No changes to commit"
          fi
